# Ankur Patel
## 11/1/2019
## p.ankur.715@gmail.com

# Arrest Data from 2010 to Present

This dataset reflects arrest incidents in the City of Los Angeles dating back to 2010. This data is transcribed from original arrest reports that are typed on paper and therefore there may be some inaccuracies within the data. Some location fields with missing data are noted as (0.0000°, 0.0000°). Address fields are only provided to the nearest hundred block in order to maintain privacy. This data is as accurate as the data in the database. Please note questions or concerns in the comments.

In [1]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://ewscripps.brightspotcdn.com/dims4/default/2bf40c2/2147483647/strip/true/crop/1100x619+0+2/resize/1280x720!/quality/90/?url=https%3A%2F%2Fmediaassets.ksby.com%2Fcordillera-network%2Fwp-content%2Fuploads%2Fsites%2F2%2F2018%2F11%2F04180116%2Farrest.jpg", width=600, height=200)

In [2]:
import pandas as pd

In [3]:
# read csv and view sample
df = pd.read_csv("Arrest_Data_from_2010_to_Present.csv")
df.head(100)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
0,4248313,02/24/2015,1310.0,20,Olympic,2022,37,M,H,5.0,Burglary,F,459PC,BURGLARY,5TH,WILTON,"(34.0653, -118.314)"
1,191811472,05/03/2019,1700.0,18,Southeast,1802,23,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)"
2,4254777,02/26/2015,2010.0,19,Mission,1985,22,M,H,6.0,Larceny,M,459.5PC,SHOPLIFTING,8300 VAN NUYS BL,NaN,"(34.2216, -118.4488)"
3,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)"
4,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)"
5,5615701,04/30/2019,1100.0,9,Van Nuys,901,2,F,H,NaN,NaN,D,300(B)WIC,NaN,RAYMER,SEPULVEDA BL,"(34.2149, -118.4674)"
6,4256466,02/28/2015,1430.0,18,Southeast,1824,22,M,B,5.0,Burglary,F,459PC,BURGLARY,103RD,HICKORY,"(33.947, -118.2594)"
7,4256564,02/28/2015,1715.0,10,West Valley,1039,16,M,H,3.0,Robbery,F,211PC,ROBBERY,VANOWEN,WOODLEY,"(34.1939, -118.4836)"
8,5616892,05/01/2019,1710.0,12,77th Street,1245,28,F,B,3.0,Robbery,F,211PC,ROBBERY,VERMONT,FLORENCE,"(33.9746, -118.2918)"
9,5617003,05/01/2019,1010.0,16,Foothill,1601,39,M,H,NaN,NaN,O,21 841A1US,NaN,FOOTHILL BL,PAXTON,"(34.2868, -118.4081)"
10,4256815,03/01/2015,110.0,17,Devonshire,1794,22,M,H,8.0,Other Assaults,M,243(A)PC,BATTERY ON PERSON,VANALDEN,BRYANT,"(34.2251, -118.5372)"
11,5618079,05/02/2019,1520.0,14,Pacific,1415,58,M,B,5.0,Burglary,F,459PC,BURGLARY,ROSE,FREDERICK,"(34.0027, -118.4653)"
12,4257858,03/02/2015,1710.0,1,Central,163,34,M,H,3.0,Robbery,F,211PC,ROBBERY,700 S BROADWAY,NaN,"(34.0452, -118.2534)"
13,190112234,04/16/2019,1450.0,1,Central,123,54,F,H,24.0,Miscellaneous Other Violations,M,41.45CLAMC,ILLEGAL POSSESSION OF SHOPPING CART,1ST,SPRING,"(34.053, -118.2444)"
14,190112235,04/26/2019,1505.0,1,Central,152,57,M,H,18.0,Drunkeness,M,41.27CLAMC,DRINKING IN PUBLIC,6TH,HILL,"(34.0481, -118.2542)"
15,190112236,04/26/2019,1515.0,1,Central,135,35,M,W,24.0,Miscellaneous Other Violations,M,41.45CLAMC,ILLEGAL POSSESSION OF SHOPPING CART,2ND,MAIN,"(34.0514, -118.2451)"
16,190112237,04/26/2019,1845.0,1,Central,162,29,M,B,6.0,Larceny,M,459.5PC,SHOPLIFTING,700 W 7TH ST,NaN,"(34.048, -118.2577)"
17,190112276,04/27/2019,2215.0,1,Central,163,35,M,H,17.0,Liquor Laws,I,25620ABP,DRINKING ALCOHOL*******,7TH,FLOWER,"(34.0438, -118.2547)"
18,190112289,04/26/2019,1745.0,1,Central,119,39,M,B,24.0,Miscellaneous Other Violations,M,602(1)PC,REFUSE TO LEAVE LANDS UPON REQUEST,700 N VIGNES ST,NaN,"(34.0552, -118.2322)"
19,190210375,04/23/2019,1820.0,2,Rampart,257,55,M,H,NaN,NaN,I,41.47.2LAMC,NaN,1400 W 6TH ST,NaN,"(34.0562, -118.2673)"
20,190210376,04/23/2019,1505.0,2,Rampart,245,27,M,H,NaN,NaN,I,41.47.2LAMC,NaN,2200 W 6TH ST,NaN,"(34.0601, -118.2761)"
21,190210377,04/27/2019,1205.0,2,Rampart,245,42,M,H,NaN,NaN,I,41.47.2LAMC,NaN,2200 W 6TH ST,NaN,"(34.0601, -118.2761)"
22,190210378,04/22/2019,1525.0,2,Rampart,245,31,M,W,NaN,NaN,I,41.18(A)LAM,NaN,WILSHIRE,ALVARADO,"(34.0597, -118.2795)"
23,190210379,04/22/2019,1525.0,2,Rampart,245,56,M,H,NaN,NaN,I,41.18(A)LAM,NaN,WILSHIRE,ALVARADO,"(34.0597, -118.2795)"
24,190210380,04/22/2019,1555.0,2,Rampart,245,28,M,W,NaN,NaN,I,41.18(A)LAM,NaN,WILSHIRE,ALVARADO,"(34.0597, -118.2795)"
25,190210381,04/23/2019,1600.0,2,Rampart,245,47,M,W,NaN,NaN,I,41.45(C),NaN,2200 W 6TH ST,NaN,"(34.0601, -118.2761)"
26,190210382,04/23/2019,1650.0,2,Rampart,245,32,F,H,NaN,NaN,I,41.27(C)LAM,NaN,2200 W 6TH ST,NaN,"(34.0601, -118.2761)"
27,190210383,04/26/2019,2015.0,2,Rampart,257,69,M,H,NaN,NaN,I,41.27(C)LAM,NaN,UNION,6TH,"(34.0569, -118.2689)"
28,190210384,04/24/2019,2025.0,2,Rampart,246,40,M,W,NaN,NaN,I,640(B)(3)PC,NaN,600 S ALVARADO ST,NaN,"(34.0596, -118.2749)"
29,190210387,04/25/2019,1820.0,2,Rampart,275,52,M,B,NaN,NaN,I,41.18(D)LAM,NaN,BEACON,OLYMPIC,"(34.0498, -118.2754)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,190210454,04/27/2019,1530.0,2,Rampart,256,45,M,H,17.0,Liquor Laws,I,25620ABP,DRINKING ALCOHOL*******,600 LITTLE ST,NaN,"(34.0551, -118.2727)"
71,190311713,04/25/2019,1615.0,3,Southwest,376,24,M,H,17.0,Liquor Laws,I,25620(A)BP,DRINKING ALCOHOL,DALTON AV,39TH ST,"(34.0155, -118.3034)"
72,190311714,04/27/2019,1900.0,3,Southwest,375,19,M,B,NaN,NaN,I,41.24(A)LAM,NaN,3900 S WESTERN AV,NaN,"(34.0146, -118.313)"
73,190311715,04/26/2019,1830.0,3,Southwest,375,19,M,B,NaN,NaN,I,41.24(A)LAM,NaN,3900 S WESTERN AV,NaN,"(34.0146, -118.313)"
74,190311716,04/26/2019,1840.0,3,Southwest,375,27,M,B,NaN,NaN,I,41.24(A)LAM,NaN,3900 S WESTERN AV,NaN,"(34.0146, -118.313)"
75,190311717,04/26/2019,1700.0,3,Southwest,318,45,M,H,NaN,NaN,I,41.27(C)LAM,NaN,1300 W 25TH ST,NaN,"(34.0336, -118.289)"
76,190311718,04/26/2019,1700.0,3,Southwest,318,56,M,H,NaN,NaN,I,41.27(C)LAM,NaN,1300 W 25TH ST,NaN,"(34.0336, -118.289)"
77,190311719,04/26/2019,1850.0,3,Southwest,375,20,M,B,NaN,NaN,I,41.24(A)LAM,NaN,3900 S WESTERN AV,NaN,"(34.0146, -118.313)"
78,190311720,04/25/2019,1930.0,3,Southwest,335,26,M,H,17.0,Liquor Laws,I,25620(A)BP,DRINKING ALCOHOL,2200 W JEFFERSON BL,NaN,"(34.0276, -118.3229)"
79,190311721,04/26/2019,1820.0,3,Southwest,375,19,M,B,NaN,NaN,I,41.24(A)LAM,NaN,3900 S WESTERN AV,NaN,"(34.0146, -118.313)"
80,190311722,04/26/2019,1820.0,3,Southwest,375,19,M,B,NaN,NaN,I,41.24(A)LAM,NaN,3900 S WESTERN AV,NaN,"(34.0146, -118.313)"
81,190409102,04/19/2019,2115.0,4,Hollenbeck,445,32,F,B,NaN,NaN,M,647 (B)PC,NaN,2000 MARENGO ST,NaN,"(34.0571, -118.2084)"
82,190409105,04/26/2019,1640.0,4,Hollenbeck,426,26,F,H,17.0,Liquor Laws,M,25658(A)BP,SALE/ETC OF ALCOHOLIC BEVERAGE TO MINOR,4900 HUNTINGTON DR,NaN,"(34.0867, -118.1768)"
83,190409217,04/27/2019,1645.0,4,Hollenbeck,421,68,M,H,18.0,Drunkeness,M,41.27(C)LAM,DRINKING IN PUBLIC***,BROADWAY,DALY ST,"(34.0736, -118.2156)"
84,190508502,04/12/2019,1410.0,5,Harbor,523,32,M,W,NaN,NaN,M,602KPC,NaN,1500 JOHN S GIBSON BL,NaN,"(33.7677, -118.2813)"
85,190509057,04/26/2019,1400.0,5,Harbor,503,42,F,W,20.0,Disorderly Conduct,M,41.18ALAMC,LOITER/OBSTRUCT STREET/SIDEWALK/ETC,800 W LOMITA BL,NaN,"(33.7978, -118.2885)"
86,190610873,04/19/2019,920.0,6,Hollywood,666,32,M,B,NaN,NaN,I,41.24(A)LAM,NaN,1400 N HUDSON AV,NaN,"(34.0962, -118.3316)"
87,190610874,04/19/2019,915.0,6,Hollywood,666,27,M,B,NaN,NaN,I,41.24(A)LAM,NaN,1400 N HUDSON AV,NaN,"(34.0962, -118.3316)"
88,190610875,04/22/2019,910.0,6,Hollywood,668,42,M,H,NaN,NaN,I,41.24(A)LAM,NaN,WILTON,SUNSET BL,"(34.0981, -118.3136)"
89,190610876,04/23/2019,1015.0,6,Hollywood,645,34,M,W,NaN,NaN,I,56.11(10)(B,NaN,LA BREA,SUNSET BL,"(34.098, -118.3441)"
90,190610877,04/22/2019,1115.0,6,Hollywood,646,30,M,B,NaN,NaN,I,56.11.3.(1),NaN,SELMA,SCHRADER,"(34.0998, -118.3324)"
91,190610897,04/24/2019,1200.0,6,Hollywood,648,37,M,H,NaN,NaN,I,41.24(A)LAM,NaN,1600 N SAINT ANDREWS PL,NaN,"(34.0999, -118.3115)"
92,190610898,04/26/2019,810.0,6,Hollywood,666,24,M,H,NaN,NaN,I,41.24(A)LAM,NaN,1200 LODI PL,NaN,"(34.0926, -118.3234)"
93,190610900,04/26/2019,805.0,6,Hollywood,666,31,M,B,NaN,NaN,I,41.24(A)LAM,NaN,1200 LODI PL,NaN,"(34.0926, -118.3234)"
94,190610901,04/26/2019,100.0,6,Hollywood,647,28,F,W,13.0,Prostitution/Allied,M,647(B)PC,PROSTITUTION,6200 HOLLYWOOD BL,NaN,"(34.1017, -118.3245)"
95,190910031,04/16/2019,225.0,9,Van Nuys,941,25,M,W,13.0,Prostitution/Allied,M,647(B)PC,PROSTITUTION,SEPULVEDA BL,ERWIN ST,"(34.1766, -118.4589)"
96,190910041,04/15/2019,1500.0,9,Van Nuys,943,30,M,H,17.0,Liquor Laws,M,25620BP,OPEN ALCOHOLIC BEV IN PUBLIC PARK/PLACE,TYRONE AV,BURBANK BL,"(34.1721, -118.4443)"
97,190910042,04/26/2019,1030.0,9,Van Nuys,933,35,M,W,6.0,Larceny,M,22435BP,POSSESSION OF SHOPPING CART,14500 VICTORY BL,NaN,"(34.1867, -118.4487)"
98,190910048,04/27/2019,1140.0,9,Van Nuys,984,42,M,O,18.0,Drunkeness,M,41.27(C)LAM,DRINKING IN PUBLIC***,VENTURA BL,CEDROS AV,"(34.1517, -118.4531)"
99,190910049,04/27/2019,1445.0,9,Van Nuys,941,29,M,O,17.0,Liquor Laws,M,25620BP,OPEN ALCOHOLIC BEV IN PUBLIC PARK/PLACE,15200 MARTHA ST,NaN,"(34.1731, -118.464)"

### Section 1:
For this challenge, you will be asked to answer questions based on arrest incidents data of the city of Los Angeles. Information of the data set can be found here and the download link is here. Each row in the data represents the booking of an arrestee. Only consider data prior to January 1, 2019. For some questions, we specify a given date range to consider.

In [4]:
# How many bookings of arrestees were made in 2018?

import datetime
df['Arrest Date'] = pd.to_datetime(df['Arrest Date'], errors='coerce', format='%m/%d/%Y')
df['Arrest Date'].dt.year.value_counts()

# counted the number of reocrds in each year

2012    163313
2010    162416
2011    157638
2013    152673
2014    139380
2015    126154
2016    118125
2017    107651
2018    104277
2019     78500
Name: Arrest Date, dtype: int64

In [6]:
# How many bookings of arrestees were made in the area with the most arrests in 2018?

from collections import Counter
df_2018 = df[df['Arrest Date'].dt.year == 2018]
most_common,num_most_common = Counter(df_2018["Area ID"]).most_common()[0]
print("ID:", most_common)
print("How many?", num_most_common)

# in 2018, found the most common Area ID and its count

ID: 1
How many? 10951

In [8]:
# What is the 95% quantile of the age of arrestee in 2018? Only consider the following charge groups for your analysis:
# Vehicle Theft
# Robbery
# Burglary
# Receive Stolen Property

import numpy as np
# df.groupby(df["Charge Group Description"])["Age"].quantile(q=0.95)
print("Vehicle Theft:", df[df["Charge Group Description"] == "Vehicle Theft"]["Age"].quantile(q=0.95))
print("Robbery:", df[df["Charge Group Description"] == "Robbery"]["Age"].quantile(q=0.95))
print("Burglary:", df[df["Charge Group Description"] == "Burglary"]["Age"].quantile(q=0.95))
print("Receive Stolen Property:", df[df["Charge Group Description"] == "Receive Stolen Property"]["Age"].quantile(q=0.95))
print("\nmean of combined:", np.mean([49,51,53,52]))  #done in next code line but added it under this question

# calculated 95% quantile for the 4 charge groups and a mean of those

Vehicle Theft: 49.0
Robbery: 51.0
Burglary: 53.0
Receive Stolen Property: 52.0

mean of combined: 51.25

In [9]:
# There are differences between the average age of an arrestee for the various charge groups. 
# Are these differences statistically significant? 
# For this question, calculate the Z-score of the average age for each charge group. 
# Report the largest absolute value among the calculated Z-scores.

# Only consider data for 2018
# Do not consider "Pre-Delinquency" and "Non-Criminal Detention" as these charge groups are reserved for minors
# Exclude any arrests where the charge group description is not known

from scipy.stats import zscore
df1 = df[df["Charge Group Description"] != "Pre-Delinquency"]
df1 = df[df["Charge Group Description"] != "Non-Criminal Detention"]
Z = [x for x in zscore(df.groupby(df1["Charge Group Description"])["Age"].mean())]
CGD = [x for x in df1["Charge Group Description"].unique() if str(x) != 'nan']
Zscores = pd.DataFrame({"Charge Group Description":CGD, "Z-score":Z})
Zscores[Z == max(Z)]

# calculated zscores of age for each group and printed largest

   Charge Group Description  Z-score
10     Disturbing the Peace   1.7148

In [ ]:
# Felony arrest incidents have been dropping over the years. 
# Using a trend line (linear estimation) for the data from 2010 and 2018 (inclusive), 
# what is the projected number of felony arrests in 2019? Round to the nearest integer. 
# Note, the data set includes arrests for misdemeanor, felonies, etc.

from sklearn.linear_model import LinearRegression
df.dtypes
X = df[df['Arrest Date'].dt.year != 2019].value_counts()
target = df[df['Arrest Date'].dt.year == 2019].value_counts()
arr_LR = LinearRegression().fit(X, target)
arr_LR.predict(target)

# using linear regression on count of arrests from 2010-2018, finding way to predict arrests count for 2019